### ISSUE TITLE
В подсказке показывает все компоненты, а не подходящие по названию

### ISSUE THREAD

**Issue by murrometz** [matiaspub/bxCompSnpt#3]
Привет. Проблема в PhpStom 9.0 EAP 141.582

На bitrix:news правильно выдает список,
![www - cwebservershometestwww - list php - phpstorm ps-141 582 2](https://cloud.githubusercontent.com/assets/11871169/7067248/6a9d7112-ded2-11e4-9ac6-30d92bade149.png)

а если пишу просто news или catalog, то выдает 

![www - cwebservershometestwww - list php - phpstorm ps-141 582](https://cloud.githubusercontent.com/assets/11871169/7067247/6a9afa86-ded2-11e4-83ae-aec17cc860ee.png)

**Comment by matiaspub** [comment]
Это ошибка шторма, если в названии шаблона присутствует знак ":".
Можешь переименовать все шаблоны из "bitrix:xx" в "bitrix.xx".

**Comment by murrometz** [comment]
А где надо переименовать? в .xml?
переименовал. не помогает

**Comment by matiaspub** [comment]
в настройках шторма, Live Templates

**Comment by murrometz** [comment]
Спасибо, нашел. Тем не менее, когда поменял, все так же остается ....
пишу **bitrix.news** - пашет    (только когда указатель стоит в конце строки - наверно так правильно)
пишу **news** - не пашет

Вобщем работает нормально, когда в xml пишу
<template name="news"

**Comment by matiaspub** [comment]
не за что. в любом случае это к шторму ).
