### ISSUE TITLE
$_REQUEST

### ISSUE THREAD

**Issue by pilezkiy** [matiaspub/bxCompSnpt#5]
Во всех шаблонах надо экранировать $.
"$_REQUEST" заменять на "$$_REQUEST".
Иначе шаблоны не импортируются.

**Comment by matiaspub** [comment]
для Eclipse ?
спасибо, учту это в следующем релизе
если можешь, сделай пул реквест
спасибо

**Comment by pilezkiy** [comment]
Да, для Eclipse

**Comment by pilezkiy** [comment]
https://github.com/matiaspub/bxCompSnpt/pull/6

**Comment by matiaspub** [comment]
@pilezkiy обновись и проверь плиз, как работают $_REQUEST в Eclipse?
