### ISSUE TITLE
Не работает в PHPStorm 2016.3

### ISSUE THREAD

**Issue by EASemashko** [matiaspub/bxCompSnpt#7]
Не определяется в PHPStrom 2016.3

**Comment by ildarkhasanshin** [comment]
да, ошибка в каком-то сниппете: если, к примеру, оставить только первые десять сниппетов, а остальные удалить из файла временно, то в списке live templates появляется группа bitrixComponents

**Comment by Kontrael** [comment]
Смотрите мой форк. Заменил PhpStorm.xml
Теперь совместим с PHPStrom 2016.3
Методом тыка нашел косячившие компоненты, и удалил. Это были три или четыре компонента связанные с соцсетью.

**Comment by matiaspub** [comment]
[https://github.com/matiaspub/bxCompSnpt/tree/PhpStorm-2016.3-Windows](url)
вынес в отдельную ветку комит без фейловых снипетов

@Kontrael спасибо!

**Comment by ildarkhasanshin** [comment]
> https://github.com/matiaspub/bxCompSnpt/tree/PhpStorm-2016.3-Windows

где-то все равно вроде бы косяки остались
т.к. отображается и работает только десять компонентов

![img-2017-03-20-07-20-31](https://cloud.githubusercontent.com/assets/8765305/24087197/ccc9e91a-0d3d-11e7-9aff-642c1aedd554.png)

**Comment by matiaspub** [comment]
проблема исключительно в иде, опытным путем можете удалить мешающие компоненты из файла, но я думаю удалить прийдется много )

**Comment by matiaspub** [comment]
а скорей всего даже, вам нужно пересобрать локаль убунты

**Comment by ildarkhasanshin** [comment]
> а скорей всего даже, вам нужно пересобрать локаль убунты

зачем?) работаю в ней уже давно - проблем с локалью не возникало

**Comment by Kontrael** [comment]
На винде подобной проблемы нет. 
![2017-03-20_14-32-46 2](https://cloud.githubusercontent.com/assets/10301895/24098246/9ec478a4-0d7a-11e7-864b-916d1895c1e6.png)
Можете пойти по моему пути и методом перебора найти косяки для своей ОС.
